# Site wide configuration

title: Spartan Code Blog
locale: en_US
description: Where magic is.
logo: sitelogo2.gif
search: true
baseurl: ""
url: "http://blog.spartan-code.com/"
#url: 'http://127.0.0.1:4000/'

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
# gems:
#   - jekyll-sitemap
gems: ['kramdown', 'jekyll-sitemap']

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

#include: [".htaccess"]
#exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
# exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

site:
  owner:
    disqus-shortname: spartancode

# Site owner
owner:
  name: Martin Prado
  avatar: yo.png
  email: martin@spartan-code.com
  disqus-shortname: spartancode
  twitter: pirateuy
  facebook: #username
  github: pirata21
  stackexchange: http://stackoverflow.com/users/3469082/pirata21
  linkedin: https://uy.linkedin.com/in/martinprado1
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
